# Generated by Django 5.2.17 on 2026-10-02 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotOrderReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.order')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('actor', 'request_id'), name='flowza_bot_request_unique')],
            },
        ),
    ]
